### ISSUE TITLE
Fog of war stopped working for multiplayer games

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#101]

**Comment by KennethGF** [comment]
Appears to be working today. Keep an eye on it.

**Comment by KennethGF** [comment]
More multiplayer games now and we will see the fog of war off and on.

**Comment by ExultantMonkey** [comment]
It affects single player as well. It might well be that last tidy I did

**Comment by KennethGF** [comment]
CivilizationMapData appears to be where this is evaluated. I cannot figure it out.

**Comment by bote-reginald** [comment]
seems to come from exceeding value for ScanStrength and SensorRange from Data files for Ships/Stations?/Structures? ... we try to solve it soon
