### ISSUE TITLE
Wormholes without linkage to a destination give null exception when ship enters.

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#105]

**Comment by ExultantMonkey** [comment]
I should have a fix for this in later this evening

**Comment by bote-reginald** [comment]
I doubled public MapLocation? WormholeDestination { get; set; }  into Sector.cs to have a destination also for (empty) sectors not having a system with planets inside

**Comment by KennethGF** [comment]
Wormhole with no link no longer crashes the game. Linked ones working nicely still. Do like the idea about some ships randomly getting sent far across the map.
