### ISSUE TITLE
Shipyards with 1,2,3,4 bays or 2,4,6,8 bays or 4,6,8,10 bays?

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#106]
Think that Mike had the later and Iceman the first option. Should we take the middle? Playtest along with raw material issues.

**Comment by bote-reginald** [comment]
more bays are like a ship building list and minimize the micro management

**Comment by ExultantMonkey** [comment]
I must that I'm conflicted on this. First, there is in universe, where shipyards can be working on dozens of ships at once. But when it comes to in the game - do people really need the ability to churn out dozens of ships a turn, even if they've got the resources?

**Comment by KennethGF** [comment]
Could make it a game option. We fixed an issue with deuterium production so that is not such a bottle neck anymore. Just going to leave it alone for now and see what happens with more play testing.

**Comment by DanOfStarfleet** [comment]
Maybe Utopia Planitia shipyards could have more construction bays!!!

**Comment by ExultantMonkey** [comment]
I think I'm leaning more on to the lower option, with a special building like Utopia Planetia that increases it by 2? Which would range it from 1,2,3,4 to 3,4,5,6

**Comment by KennethGF** [comment]
Go with what we have for now.
