### ISSUE TITLE
Problem with colony upon population reducing events

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#11]
http://star-trek-supremacy.proboards.com/post/6239/thread

A bug I noticed is that when the system population is decimated, the production values are still the same as the turn before and if you don't reallocate your workforce, your planet has the same production output it had before the population was reduced.

Also, one event killed off my entire system population, the planet was still under my control, but I couldn't recolonize it nor did I gain any new population on it, even the system population ifo was missing, it wasn't 0, it was just nonexistent. I was playing as the Dominion.

**Comment by bote-reginald** [comment]
"too old" - maybe not relevant anymore
