### ISSUE TITLE
Is Assimilation, at 20% risk, too much? (CombatEngine)  

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#114]
Keeping a eye on how assimilation might imbalance the game in Borg favor. Need more multiplayer testing. Will reduce the BaseChanceToAssimilate if it is.

**Comment by ExultantMonkey** [comment]
I think it is. I had a quick game as Borg the other day. Whilst I think you've got their power correct, with the ships that they assimilated, I would have been able to destroy all opposition ships without problem.

Maybe decrease it to 5%?

**Comment by KennethGF** [comment]
set to 5 %
