### ISSUE TITLE
Unable to save game

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#117]
Start a game
Press end turn
Go to main menu
Press save

The "Save" and "Cancel" boxes in the save dialog are disabled, and will not reenable

Autosaving still works, so it seems a GUI problem

**Comment by HappyGino** [comment]
I read on the forum that by going to the Intel and right clicking to go to the save menu, it unlocks the save option. I tried it and it really works. Maybe there is something to look in that parameter.

**Comment by KennethGF** [comment]
Good find. 😎

ken

**Comment by HappyGino** [comment]
Now the thing is to find and repair this bug, lol
Happy to help!

Bonne journée! Have a nice day!

________________________________
De : Kenneth Of Borg <notifications@github.com>
Envoyé : Thursday, October 17, 2019 10:11:18 PM
À : BotF2/BotF2 <BotF2@noreply.github.com>
Cc : HappyGino <emilgo47@hotmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [BotF2/BotF2] Unable to save game (#117)

Good find. 😎

ken
