### ISSUE TITLE
Want cloak and camouflage strength int to work with a scan for hidden ships 

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#119]
Code cloak and camouflage strength int value vs a scan strength that would reveal the hidden ships for combat....

**Comment by KennethGF** [comment]
Want a science ship to improve on the detection of hidden ships.

**Comment by ExultantMonkey** [comment]
There is something for this somewhere in the code, I seem to recall it being somewhere it the WPF code, but don't take my word on that

**Comment by KennethGF** [comment]
Yes, it appears that TechObjectInfo.xaml gets ScanPower and SensorRange from the ship data and these values are displayed in the science / encyclopedia screen. Hope we can use this data to calculate a decloaking decamouflage function on scan. More more for this for science and scout ships.

**Comment by KennethGF** [comment]
_scanPower and _sensorRange are properties of the OrbitalDesign class in Core

**Comment by KennethGF** [comment]
Thinking this should be decided in Core/ Combat / CombatUnit using the bool value of IsCloaked and IsCamouflaged

**Comment by KennethGF** [comment]
done
