### ISSUE TITLE
Credits, It's the economy stupid

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#125]
How do credits work? Do credits work?

**Comment by KennethGF** [comment]
colony.cs TaxCredit
_creditsFromTrade = new Meter(); public Meter CreditsFromTrade

                            case BonusType.Credits:
                            case BonusType.PercentCredits:
                            case BonusType.PercentTotalCredits:
                                propertyChanges.Add("Credits");
                                break;
                            case BonusType.PercentTradeIncome:
                                propertyChanges.Add("Credits");
                                foreach (var tradeRoute in _tradeRoutes)
                                    tradeRoute.NotifyLocalPlayerCreditsChanged();
                                break;

**Comment by KennethGF** [comment]
ready for play testing

**Comment by KennethGF** [comment]
Open this to update trade rout credits

**Comment by bote-reginald** [comment]
Credits work but need more attention ... on the way to find out more
