### ISSUE TITLE
Dominion loads wrong home world system some time

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#128]
noticed this off and on in game testing

**Comment by KennethGF** [comment]
Now have seen the Borg do the same, not in their nebula.
03:46:03.659 [8] ERROR General Supremacy.Tech.TechObjectDesign.CanSpawn() - Cannot spawn SHIELD_GENERATOR at location (26, 1) because the sector is not owned by BORG.

**Comment by bote-reginald** [comment]
didn't noticed that problem recently
