### ISSUE TITLE
Assault System target shields

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#14]
Want to see if shields prevent you from landing troops. If so then want target shields to be an option in system assault.

Look in InvasionArena (SupremacyCore.Combat) to add more detail getting at planet shield source
while([tech level is high enough]) { [Code to execute that lets you get specific in taking out shields...] }

**Comment by bote-reginald** [comment]
if colonyShields not down, you can't land troops. As well, if you don't have transport ship (with troops) at assault. Would like to have tooltips on buttons (or other info) for gamer why button land troops is grayed out.

**Comment by KennethGF** [comment]
Agree

ken

**Comment by KennethGF** [comment]
refactored
