### ISSUE TITLE
sabotage without orders to do so

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#144]
This should be under player control to order. Not an auto function as it appears to work as.

06:51:43.894 [1] DEBUG General - GameController.ProcessSitRepEntries(): ###################### SUMMARY: 1 industry facility/facilities sabotaged on Cardassia.
06:51:43.895 [1] DEBUG General - GameController.ProcessSitRepEntries(): ###################### SUMMARY: Our agents stole 1258 credits from the treasury on Cardassia.

**Comment by ExultantMonkey** [comment]
Should this be moved to orders on spy ships? I'm thinking we create orders for spy ships like so

Raid - steals credits, resources, research or map data (normal ships raid from trade routes only)
Sabotage - destroys buildings

**Comment by KennethGF** [comment]
That would be a clean way to handle it.

**Comment by KennethGF** [comment]
Confusing random event with directed spy activity.
