### ISSUE TITLE
Problems when assimilating

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#156]
When a minor race ship has been assimilated, it shows up both in the Borg's assimilated assets, and the oppositions escaped ships.

Minor race ships seem to have a total fuel capacity of 0 when assimilated, which means they can't move.

I also can't scrap them

**Comment by KennethGF** [comment]
Minor race ships all had fuel reserves set to 0. Updated this in the TechObjectDatabase to 4, like the empires. No change in code needed.

**Comment by KennethGF** [comment]
The scrap is still and issue. Appears to be in the new gamelog setting. Gamelog.Client.General.....

**Comment by KennethGF** [comment]
Appears to be resolved by improvements in creating the new fleet that owns the assimilated ship. Using the Ship CreateFleet() method.
