### ISSUE TITLE
Combat with Spy ship where no friendly ship is seen on left

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#160]
The spy ship is in camouflage. Combat window opens with no ships seen on the left side. Message at the top says we have been defeated. Click close on the combat window and game fails to progress saying combat is being resolved. 

15:36:01.486 [1] DEBUG Combat Supremacy.Combat.CombatUpdate.get_IsCombatOver() - Combat: friendlyAssets (number of involved entities)=0
15:36:01.515 [1] DEBUG Combat Supremacy.Combat.CombatUpdate.get_IsCombatOver() - Combat: friendlyAssets (number of involved entities)=0
15:36:01.517 [1] DEBUG Combat Supremacy.Combat.CombatUpdate.get_IsCombatOver() - Combat: friendlyAssets (number of involved entities)=0
15:36:01.519 [1] DEBUG Combat Supremacy.Combat.CombatUpdate.get_IsCombatOver() - Combat: friendlyAssets (number of involved entities)=0
15:36:38.734 [AudioEngine] DEBUG Audio Supremacy.Client.Audio.MusicPlayer.Next() - Next at _musicPack=DefaultMusic, _musicEntry=Resources/Music\Sting Carve Gino Veziau.ogg

**Comment by KennethGF** [comment]
![combat](https://user-images.githubusercontent.com/5161174/45933789-97323280-bf48-11e8-8aaa-2e8022a6fc9d.png)

**Comment by ExultantMonkey** [comment]
Will try and sort it this week
