### ISSUE TITLE
Combat Assets etc needs simplifying greatly

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#169]
Currently, we're creating simplified models of the ships in the assets, but then accessing the originals to work things out, even going a step above that to the design itself, then applying our effects to the simplified models during combat, then updating the originals. What kind of lunacy is that?

**Comment by KennethGF** [comment]
Trying to understand the problem. Sorry for the trouble.  OrbitalDesign.cs "reads" the value out of the TechObjectDatabase and has a public int for CamouflagedStrength in SupremacyCore. Then ShipDesign CamouflagedStrength hides OrbitalDesign's value for CamouflagedStrength.  Is the problem how we access the value of CamouflagedStrength?

**Comment by ExultantMonkey** [comment]
It's not a problem with what's going on at the moment, it's a problem with the original design of the thing. There are so many layers, all of which we access anyway, that I cannot help but question it. It might well end up being the best way to do things, but I intend to take a good look at it at some point to see if this is really the case
