### ISSUE TITLE
Spy infiltration to show in intel screen and blame others

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#184]
Want to bring in the feature from the original game where you can blame someone else when your spy sabotaged a system. Want to bring enemy systems into the intel screen. Want to insert spy network with the spy ships that then persist after the ships.

**Comment by KennethGF** [comment]
We would need to see where they still match up. It would be nice to review.
You could test it out by replacing in your Resources folder.

Look at the download section in the forums. We have a new, but announced
release, for testing. Best to test any changes there.

Thanks for taking Trump off our hands, if just for a short while.

Ken

**Comment by DanOfStarfleet** [comment]
I found something about the blame on the BOTF original game, go to this link about the intel!
https://www.armadafleetcommand.com/onscreen/botf/viewtopic.php?f=225&t=2311

**Comment by KennethGF** [comment]
Thank you. Think this is going to help as we build out intel. 👍

**Comment by KennethGF** [comment]
Will want spy ships to collect data from the current infiltrated colony, store data in the spy ship object and then display it in the Spy Report tab of affairs / intel screen.
