### ISSUE TITLE
Option to *not* confine species to there quadrant

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#189]
Unable to build maps. 
-There has been a request for an option *not* to confine species to their own quadrants to make the map even more random
- Appear to not be able to build smaller maps more than large ones
- Appear to have problem putting borg and or Dominion in their nebula

**Comment by KennethGF** [comment]
Make it a button on the options menu for Map: Star Trek Canon vs Random vs Brexit ....

**Comment by ExultantMonkey** [comment]
Doing some tweaking on the code for this
