### ISSUE TITLE
Possible infinite loop in DoProduction

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#20]
I'm not entirely sure how this happened, it shouldn't be possible

```
while ((industry > 0) && ((!colony.BuildQueue.IsEmpty()) || colony.BuildSlots[0].HasProject))
```

**Comment by bote-reginald** [comment]
maybe..
while ind > 0 AND   (as far as ind is available)
- BuildQueue = Facilities OR
- B.-Slots = Ships  (Slot 1, 2, 3, ...)

**Comment by ExultantMonkey** [comment]
I've been looking in to it some more and I don't think it's an infinite loop, just takes a long time after me refactoring it. I may have to have a rethink

**Comment by KennethGF** [comment]
Have seen apparent endless Processing Turn, Processing Ship Production just now as I am working on other issues.

**Comment by ExultantMonkey** [comment]
The cause for it taking so long is that it spends a lot of time writing to the log. #17 will fix this as it adds a missing if statement that makes it only write to the log if tracing for production is enabled

**Comment by KennethGF** [comment]
Thanks. Reminds me of an issue in online games to look at. Host appears to
update each remote pc one at a time and that take incrementally longer each
turn. Seams to be starting over from turn one rather than adding to the
data sent before. Will add to issue list later.

ken

**Comment by ExultantMonkey** [comment]
With the logging turned off, it now takes less than a second, but it would seem that this can still occur, so will need looking at in some more detail

**Comment by KennethGF** [comment]
Thank you!

ken

**Comment by KennethGF** [comment]
Just cloned onto a different PC and have no issue with ship production
hangup. Just a local issue for me. Will re-clone the hung up PC.

On Mon, Jan 8, 2018 at 11:13 AM, Kenneth Flanagan <kenneth.of.borg@gmail.com
> wrote:

> Thank you!
>
> ken
>
> On Jan 8, 2018 10:45 AM, "David William Richmond Davies-Jones" <

**Comment by ExultantMonkey** [comment]
Closing this until I can reproduce it
