### ISSUE TITLE
Lost the planet view detail & images in Galaxy screen. Was not working in the last test release.

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#259]

**Comment by KennethGF** [comment]
Is this the result of removing Native as in no more fog of war?

**Comment by KennethGF** [comment]
Documenting features of the issue here:

https://star-trek-supremacy.proboards.com/thread/745/planets-star-system-panel

**Comment by bote-reginald** [comment]
even the HomeSystem is not EXPLORED - if not, no planets are shown (I just guess that, will have a more deep look)
Supremacy.UI.GalaxyGridPanel.IsScanned() - location = (18, 7), playerEmpire = Klingons, IsScanned = True, IsExplored = False

**Comment by bote-reginald** [comment]
oh, sorry, wrong info - both are true
location = (18, 17), playerEmpire = Klingons, IsScanned = True, IsExplored = True

**Comment by bote-reginald** [comment]
see https://github.com/BotF2/BotF2/commit/c20f177c7a2eb7180b4dca7d2131d77665867ef8 ...I'm trying to do more investigation there ... if SupportsPlanets = true, planets are shown !!

**Comment by KennethGF** [comment]
code workaround on systems that support planets
