### ISSUE TITLE
Station construct orders not cancelled after battle

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#26]
If you have a fleet in an enemies system, and there is an enemy construction ship there with orders to build a station, engage it in battle, it will retreat to an adjacent sector without a system. The order will stay however, and it will attempt to construct the station in a sector with no system, resulting in a null reference. The construct order needs to be cleared on retreat

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SupremacyCore
  StackTrace:
   at Supremacy.AI.UnitAI.DoTurn(Civilization civ) in C:\Users\dwrj8\Repositories\BotF2\SupremacyCore\AI\UnitAI.cs:line 110
```

**Comment by KennethGF** [comment]
So this is how we can improve tracing errors?

ken

**Comment by ExultantMonkey** [comment]
Wrong thread @KennethGF 😄
