### ISSUE TITLE
CombatEngine Collection modified during enumeration, a sync thing?

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#281]
While woking on trade routes have seen a random error in CombatEngin in IsCombatOver with the line [ return (_assets.Count(assets => assets.HasSurvivingAssets) <= 1) ]. 'Collection was modified; enumeration  operation my not execute.' Sounds like _assets.count via HasSurvivingAssets is getting changed, now and then, at a point where it interferes with the count. 

This might be a result of slow combat with a lot of active gamelogs. If it stays an issue can look to things like synch and threading to deal with it.

**Comment by KennethGF** [comment]
An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code

Additional information: Collection was modified; enumeration operation may not execute.

If there is a handler for this exception, the program may be safely continued.

**Comment by KennethGF** [comment]
Appears related to be we remove a ship while evaluating. Like a construction ship when two are building a station so change the count of _assets during count(). Works now by adding ToList() to both foreach assets and foreach CombatShips an nonCombat ships in "foreach (CombatAssets civAssets in _assets.ToList())"

**Comment by KennethGF** [comment]
Appears to still be an issue. Will try synchlock next.

**Comment by KennethGF** [comment]
Put in a Try Catch and wait for IsCombatOver

**Comment by KennethGF** [comment]
An exception was thrown by the target of a call.
   At System.RuntimeMethodHandle.InvokeMethod (Object target, Object [] arguments, Signature sig, Boolean constructor)
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal (Object obj, Object [] parameters, Object [] arguments)
   At System.Delegate.DynamicInvokeImpl (Object [] args)
   Ã Supremacy.Utility.AsyncHelper.AsyncInvokeCallback (Object state)
   At System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
   Ã System.Threading.ThreadPoolWorkQueue.Dispatch ()
   At System.Threading._ThreadPoolWaitCallback.PerformWaitCallback ()
----------------------------------------
The object reference is not defined to an instance of an object.
   Ã Supremacy.WCF.SupremacyService.SendCombatUpdateCallback (CombatEngine engine, CombatUpdate update)
----------------------------------------

An exception was thrown by the target of a call.
   At System.RuntimeMethodHandle.InvokeMethod (Object target, Object [] arguments, Signature sig, Boolean constructor)
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal (Object obj, Object [] parameters, Object [] arguments)
   At System.Delegate.DynamicInvokeImpl (Object [] args)
   System.Windows.Threading.ExceptionWrapper.InternalRealCall (Delegate callback, Object args, Int32 numArgs)
   System.Windows.Threading.ExceptionWrapper.TryCatchWhen (Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
----------------------------------------
The index was out of bounds. It must not be negative and must be smaller than the size of the collection.
Parameter name: index
   At System.ThrowHelper.ThrowArgumentOutOfRangeException (ExceptionArgument argument, ExceptionResource resource)
   At System.SZArrayHelper.get_Item [T] (Int32 index)
   Ã Supremacy.Client.CombatWindow.HandleCombatUpdate (CombatUpdate update)
   Ã Supremacy.Client.CombatWindow.OnCombatUpdateReceived (DataEventArgs`1 args)

**Comment by HappyGino** [comment]
I had a similar combat occurring when I haven't discovered the Cardassians yet but I could only see them in the Intel window (spy Report) In fact, combat never occurred since it crashed the test game . 
"Index Out of bounds....It must not be negative and must be smaller than the size of the collection."
Seems to be happening after a sensor/scanner upgrade. 
System Collection maybe? **(Listening post, Subspace scanner/scanning range too large? Intelligence service maybe?)** ...Didn't even have a spy ship ready). Looks like human player has been detected from out of screen and reacts as if it was near.

**Comment by bote-reginald** [comment]
not seen this problem recently
