### ISSUE TITLE
Map, failure to build a map or bad placement

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#285]
Besides failure to build a map we can also see sectors with no minor races and major civilization home systems right next to each other.

**Comment by KennethGF** [comment]
infinity while loop where GetStarType()

**Comment by ExultantMonkey** [comment]
I must admit this is starting to annoy living heck out of me. I shall try and get it sorted

**Comment by KennethGF** [comment]
Was wondering if we could define a set of fixed maps and reference that for
saved games.
ken

**Comment by ExultantMonkey** [comment]
I believe that I have this fixed

**Comment by KennethGF** [comment]
Great work David. You are the one.

ken
