### ISSUE TITLE
Language button 

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#3]
We need to add a language button in the main menu, for the localizations!

yeah, just do code it :-) .... in my mind this will take big researching to the code. I could do a external *.bat for: - turn English (files) to French (files) or back.

**Comment by ExultantMonkey** [comment]
We could do this, or maybe we could detect the language used by the OS instead? With a falback to English if there aren't any translations for that language?

**Comment by bote-reginald** [comment]
great ! - I would prefer manual selection, with the option to mod more language. So info about available languages in some xml-file or whereever.

**Comment by ExultantMonkey** [comment]
We shall do it that way then, maybe store it in app config. The localisation code will probably need a rework to handle this, but this is something that I've been wanting to do for a while anyway

**Comment by KennethGF** [comment]
Great

ken

**Comment by bote-reginald** [comment]
no priority atm
