### ISSUE TITLE
Endless Processing Ship Production

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#30]
On first or second turn of a game stopped at an apparent endless loop of Processing Ship Production. 
Hit pose and continue in VS and see it in files like GrapihcsDeviceManger..cs, ClientApp.xaml.cs and Dialog.cs. Get it while playing with many minor races and no minor races. 
![shipprocessing](https://user-images.githubusercontent.com/5161174/34940170-cd3ed56c-f9ab-11e7-8dd6-00a59dbbc1f8.png)

**Comment by KennethGF** [comment]
Issue appears to be gone if I play with Borg set to No, not in game as empire. Also took away their shipyard for Early tech level game and also no Processing Ship Production loop in the first few turns.

**Comment by KennethGF** [comment]
Copied the setting for Federation shipyard in TechObjectDatabase.xaml into the Borg shipyards. Did not get any issues with the loop. Wonder if the extreme setting for them had been messing with AI or whatever?

**Comment by ExultantMonkey** [comment]
That may be why I can't reproduce it. I shall take a look at it again in a bit with Borg in game

**Comment by KennethGF** [comment]
Please

ken

**Comment by ExultantMonkey** [comment]
Do you have a copy of the TechObjectDatabase that is known to cause it? As I still can't reproduce it even with the Borg as an empire, and I haven't updated the TechObjectDatabase for a while on this end

**Comment by KennethGF** [comment]
ken

**Comment by KennethGF** [comment]
Opp, replied on my smarter-than-me phone with an empty email.

 Attached here is that TechObjectDatabase.xml

If this does not reproduce the issue with Borg set to higher tech levels
than just let it go. Will keep an eye our for it showing up again.

Ken

On Mon, Jan 15, 2018 at 3:49 PM, Kenneth Flanagan <kenneth.of.borg@gmail.com
> wrote:

>
>
> ken
>
> On Jan 15, 2018 2:18 PM, "David William Richmond Davies-Jones" <

**Comment by ExultantMonkey** [comment]
You can't email attachments to Github

**Comment by KennethGF** [comment]
Opps again, just sent it to your Gmail address. Looked like an image display issue so wonder if there could have been some limit on the number of bays called for in the larger yards? Thanks for looking at it.

**Comment by KennethGF** [comment]
No longer seeing this issue. Will close it but keep an eye open.

**Comment by ExultantMonkey** [comment]
I'm guessing that it's a very fringe case. We will crack it eventually, but god knows when
