### ISSUE TITLE
XML2CSV needs tidying up

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#326]

**Comment by bote-reginald** [comment]
to own class would be ok, but I want to have an output of the data exactly used in that game which was just started

**Comment by ExultantMonkey** [comment]
Hmmm, maybe a compromise. Create a new library specifically for data import/export. It can still be used for the data that is loaded in the game, as well as an executableEither way, dumping the data should not be the default, it needs to be done only when requestedOn 23 Aug 2019 18:16, bote-reginald <notifications@github.com> wrote:to own class would be ok, but I want to have an output of the data exactly used in that game which was just started

**Comment by bote-reginald** [comment]
I was glad to get it running this way... new library...how ??
correct...once i planned to export only if GameOption-XML2CSV is activated, Not implemented yet... always other stuff to do

**Comment by ExultantMonkey** [comment]
Maybe it's best if I do itOn 23 Aug 2019 22:16, bote-reginald <notifications@github.com> wrote:I was glad to get it running this way... new library...how ??
correct...once i planned to export only if GameOption-XML2CSV is activated, Not implemented yet... always other stuff to do

**Comment by bote-reginald** [comment]
Thank you
