### ISSUE TITLE
CS0156	A throw statement with no arguments

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#394]
Was playing the test game I found that at the start, we cannot build a Martial Law object as the first building. There must be at least one building (farm or replication or whatever) in the queue, because it sends this error. Unless my copy is corrupted...

Error	CS0156	A throw statement with no arguments is not allowed outside of a catch clause	
     
("value", "Value must be >= MinValue.");

                _value = value;
            }
            else
            {
                throw;
            }
        }

        public Percentage(double value)
            : this((float)value)
        {
            if (value > MaxValue)
                throw new ArgumentOutOfRangeException("value", "Value must be <= MaxValue.");
        }

**Comment by HappyGino** [comment]
//The last message (up) was an error fix trial that went wrong. 

//Seems like using this new method, it fixes the problem of Martial Law as first building.
//Haven't approved yet...Still testing if it breaks elsewhere. 
//Changes on 2 lines (see NewMethod below) . 
//Since this fix has been applied, no more issue of Martial Law happened.


        #region Constructors
        public Percentage(float value)
        {
            if (float.IsNaN(value) || float.IsInfinity(value))
                throw new ArgumentException("Value cannot be NaN or Infinity.", "value");

            value = NewMethod(value);

            if (value > float.MaxValue)
                throw new ArgumentOutOfRangeException("value", "Value must be <= MaxValue.");
            if (value < float.MinValue)
                throw new ArgumentOutOfRangeException("value", "Value must be >= MinValue.");

            _value = value;
        }

        private static float NewMethod(float value)

**Comment by KennethGF** [comment]
Good catch. We should look deeper into the math error though. Sounds like a
fix but want to see if we have it all.

ken

**Comment by HappyGino** [comment]
I also sent another bug issue with the fix and the 2 files for comparison about the save/load system that was creating an error message. Applied the suggested fix and it worked but awaiting approval.

Bonne journée! Have a nice day!

________________________________
De : Kenneth Of Borg <notifications@github.com>
Envoyé : Thursday, October 17, 2019 9:11:12 PM
À : BotF2/BotF2 <BotF2@noreply.github.com>
Cc : HappyGino <emilgo47@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [BotF2/BotF2] CS0156 A throw statement with no arguments (#394)

Good catch. We should look deeper into the math error though. Sounds like a
fix but want to see if we have it all.

ken

**Comment by KennethGF** [comment]
In California for the wedding. Will look when I can. Thanks

ken

**Comment by bote-reginald** [comment]
two commits today solving the problem with MARTIAL LAW and similar
