### ISSUE TITLE
Saving game and loading back creates an error

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#396]
Rewrote shorter message down below.

**Comment by HappyGino** [comment]
**//Unmodified file**         


  AddToJumpList(
                    jumpList,
                    savedGame,
                    savedGame.IsAutoSave
                        ? _autoSaveGameTitle.Value
                        : Path.GetFileNameWithoutExtension(savedGame.FileName),
                    entryExe,
                    iconFiles[savedGame.LocalPlayerEmpireName].IconFile,
                    savedGame.IsMultiplayerGame ? multiplayerCategory : singlePlayerCategory,
                    savedGame.IsMultiplayerGame ? multiplayerDescription : singlePlayerDescription);
            }

            Application.Current.Dispatcher.Invoke(
                DispatcherPriority.Background,
                (Action)
                (() =>
                 {
                     if (jumpListCreated)
                     {
                         JumpList.SetJumpList(
                             Application.Current,
                             jumpList);

**Comment by HappyGino** [comment]
**//Modified file**   

  foreach (var savedGame in savedGames)
            {
                AddToJumpList(
                    jumpList,
                    savedGame,
                    savedGame.IsAutoSave
                        ? _autoSaveGameTitle.Value
                        : Path.GetFileNameWithoutExtension(savedGame.FileName),
                    entryExe,
                    iconFiles[savedGame.LocalPlayerEmpireName].IconFile,
                    savedGame.IsMultiplayerGame ? multiplayerCategory : singlePlayerCategory,
                    savedGame.IsMultiplayerGame ? multiplayerDescription : singlePlayerDescription);
            }

            object v = _ = Application.Current.Dispatcher.Invoke(
                DispatcherPriority.Background,
                (Action)
                (() =>
                 {
                     if (jumpListCreated)
                     {
                         JumpList.SetJumpList(
                             Application.Current,
                             jumpList);

**Comment by bote-reginald** [comment]
committed by https://github.com/BotF2/BotF2/commit/ce7d363722f01b5369370ee8d81ab6c17118bff3
