### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#399]
**There is something about the Combat window and out of range exception that is creating a bug.
There was no enemy to combat in all the screen . Cardassians where allied with Federation and all minors were joined or on open border, except for the Mokra, which was Neutral.**

System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=L'index était hors limites. Il ne doit pas être négatif et doit être inférieur à la taille de la collection.
Nom du paramètre : index
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Supremacy.Client.CombatWindow.HandleCombatUpdate(CombatUpdate update) in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyClient\CombatWindow.xaml.cs:line 129
   at Supremacy.Client.CombatWindow.OnCombatUpdateReceived(DataEventArgs`1 args) in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyClient\CombatWindow.xaml.cs:line 103

**Comment by KennethGF** [comment]
Thanks. We can have a look.

ken

**Comment by HappyGino** [comment]
`The ArgumentOutOfRangeException type is a subclass of ArgumentException class. This exception type is thrown when the value of an argument is outside of the allowable range. For example, this can be thrown when you pass negative numbers to a function that accepts only positive numbers.`

Now I understand better what ArgumentOutOfRangeException means.

**Comment by HappyGino** [comment]
**These are the 3 Call Stacks. Seems to be missing some files or lines in this version. It calls something that isn't there or doesn't have the same value as what is expected.
Hope it helps**

 SupremacyClient.exe!Supremacy.Client.CombatWindow.OnCombatUpdateReceived(Microsoft.Practices.Composite.Events.DataEventArgs<Supremacy.Combat.CombatUpdate> args) Line 103
	at C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyClient\CombatWindow.xaml.cs(103)
-----------------------

SupremacyClient.exe!Supremacy.Client.ClientApp.StartClient(string[] args) Line 503
	at C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyClient\ClientApp.xaml.cs(503)
------------------------

SupremacyClient.exe!Supremacy.Client.ClientApp.EntryPoint.Main(string[] args) Line 396
	at C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyClient\ClientApp.xaml.cs(396)

**Comment by KennethGF** [comment]
Chris and I Tired to update the opening of combat window in gameengine.cs but generated a frozen combat process at some other point further on. Something like no ships left still generating a new combat window. (Do we need more checking for zero assets on an updated value?)

Will look at this again later, here is the new code we tried.

    void DoCombat(GameContext game)
        {
            var combatLocations = new HashSet<MapLocation>();
            var invasionLocations = new HashSet<MapLocation>();
            var combats = new List<List<CombatAssets>>();
            var invasions = new List<InvasionArena>();
            var fleetsAtLocation = new List<Fleet>(GameContext.Current.Universe.Find<Fleet>(UniverseObjectType.Fleet)).ToList();
  
            foreach (var fleet in fleetsAtLocation)
            {
                if (!combatLocations.Contains(fleet.Location))
                {
                        var assets = CombatHelper.GetCombatAssets(fleet.Location);
                        var fleetsOwners = fleetsAtLocation
                            .Select(o => o.Owner)
                            .Distinct()
                            .ToList();

                    if (assets.Count > 1 && fleetsOwners.Count > 1)
                    {
                        foreach (var nextFleet in fleetsAtLocation)
                            if (fleet.Owner == nextFleet.Owner || CombatHelper.WillFightAlongside(fleet.Owner, nextFleet.Owner))
                                continue;
                            combats.Add(assets);
                            combatLocations.Add(fleet.Location);
                        //}                        
                    }
                }
                if (!invasionLocations.Contains(fleet.Location))
                {
                    if (fleet.Order is AssaultSystemOrder)
                    {
                        invasions.Add(new InvasionArena(fleet.Sector.System.Colony, fleet.Owner));
                        invasionLocations.Add(fleet.Location);
                    }
                }
            }

**Comment by HappyGino** [comment]
Looks like there is an AI code that sends a combat or invasion order from a civ or a Major...
I remember that when the Klingons where totally out of my scan range (saw them with spy report), they changed from content to suspicious and then to rebellious. Wondering if that could cause combat or invasion situation... Happened also with the Terrans in another game but Terrans where already joined as minor empire.
As I see it up here, an order is definitely sent for combat or invasion but in this case, there was peace.
Just wondering....

**Comment by KennethGF** [comment]
System.ArgumentOutOfRangeException
HResult = 0x80131502
Message = The index was out of range. It must not be negative and must be smaller than the size of the collection.
Parameter name:
Source = mscorlib
StackTrace:
at System.ThrowHelper.ThrowArgumentOutOfRangeException (ExceptionArgument argument, ExceptionResource resource)
at System.SZArrayHelper.get_Item [T] (Int32 index)
at Supremacy.Client.CombatWindow.HandleCombatUpdate (CombatUpdate update) in C : \ Users \ Gino \ Documents \ BOTF2_2019_cot_13_New \ SupremacyClient \ CombatWindow.xaml.cs: line 129
at Supremacy.Client.CombatWindow.OnCombatUpdateReceived (DataEventArgs`1 args) in C: \ Users \ Gino \ Documents \ BOTF2_2019_cot_13_New \ SupremacyClient \ CombatWindow. xaml.cs: line 103
