### ISSUE TITLE
Add some words in the EN text file:

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#4]
Please add these words in the EN text file:

Military, Economic, Zoom in, Zoom out, Chat

We also need to add these words: CIVILIZATION, STATUS, TURNS, ATTITUDE, OUTGOING, INCOMING, REGARD, TRUST in the EN txt or another diplomacy text file

for DiploScreen DONE

we need the black hole, pulsar, neutron star....etc descriptions to be added in the text file

Please add also the following:
GALAXY SHAPE: Spiral, Ring, Elliptical, Cluster, Irregular
GALAXY SIZE: Tiny, Small, Medium, Large, Huge
PLANET DENSITY: Sparse, Medium, Dense
MINOR RACES: None, Few, Some, Many
TECH LEVEL: Early, Developed, Sophisticated, Advanced, Supreme

pulsar etc. DONE

Missing string about the spy, sabotage & raid ships!

SHIP_CAMOUFLAGE_STRENGTH

Missing string about the cloaked ships!! In the En.txt, suggest to add

[CLOAKED_FLEET] {0} Fleet

{0}=<SingularName>

![Image](https://bitbucket.org/repo/g445GE/images/4055695077-Fleet.jpg)

MULTIPLAYER Missing Strings: COMPUTER, UNASSIGNED, START, CANCEL

MISSING STRING: Played by Player 

![Image](https://bitbucket.org/repo/g445GE/images/2240010757-Played.jpg)

UPDATE: still missing (others should be done) - request on cloaked text - request on GALAXY SHAPE: Spiral, Ring, Elliptical, Cluster, Irregular and these others - request on MULTIPLAYER Missing Strings: COMPUTER, UNASSIGNED, START, CANCEL - played by removed :-)

**Comment by ExultantMonkey** [comment]
Copied over from #2 

We can't found the string: Played by Player

Image

eliminated "Played by", re-placed nice brackets. My suggestion for "Player": ( m ) ....m = myself, German: mich, French: moi or ma...,

Other suggestion: image by characters like ( o-o ) OR ( o^o ) OR ( /!-! ) -> in SP the name doesn't have big sense, maybe at SaveGame?, so i prefer o-o within no special characters

I think the name player must be the same name when you host a multiplayer game!! i suggest to add a text box in the new options screen to give a name to the player

In fact we can keep «Played by », we just need this appears in the en.txt

It's at
SupremacyClient/themes/Intro/GalaxyScreenView.xaml
39:

**Comment by ExultantMonkey** [comment]
I have added most of these in to en.txt. Adding them in the code will take a little bit of work

**Comment by ExultantMonkey** [comment]
SHIP_CAMOUFLAGE_STRENGTH and [CLOAKED_FLEET] {0} are the strings still not in en.txt

**Comment by bote-reginald** [comment]
always a topic but no priority atm, sorry
