### ISSUE TITLE
Newly buit Shipyards cannot be used on current turn

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#410]
**Have no reference for this as the game didn't show an error, but...
When a new shipyard is built, impossible to click on it to activate, player has to return back to the map and get back before it is clickable or wait for a new turn.  
This could be seen as a normal procedure, I mean, waiting 1 turn to activate a new shipyard, except that there should be a message appearing, saying " Shipyard is being constructed. Please wait until next turn to activate."**
Just thinking... It might also help prevent crashes if everything is being built and rushed at the same turn

**Comment by KennethGF** [comment]
Do not think this will be fixable, worth fixing in our turn-based game
