### ISSUE TITLE
UnhandledException_Error_txt

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#413]
**Game stopped unexpectedly. Not the same as 399**

Une exception a été levée par la cible d'un appel.
(An exception was raised by the target of an appeal)
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   à System.Delegate.DynamicInvokeImpl(Object[] args)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
----------------------------------------
L'index était hors limites. Il ne doit pas être négatif et doit être inférieur à la taille de la collection.
(Index out of range. Must not be negative and must be lower than the size of the collection.)
Nom du paramètre : index
   à System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   à System.SZArrayHelper.get_Item[T](Int32 index)
   à Supremacy.Client.CombatWindow.HandleCombatUpdate(CombatUpdate update) dans C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyClient\CombatWindow.xaml.cs:ligne 129
   à Supremacy.Client.CombatWindow.OnCombatUpdateReceived(DataEventArgs`1 args) dans C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyClient\CombatWindow.xaml.cs:ligne 103
----------------------------------------

**Comment by HappyGino** [comment]
Had the exact same issue mentioned up here with the new VS Test Solution that I installed on Sunday nov 10 2019. This time the TryCatch fix didn't work. 
It shows 107 errors on the whole document (0 errors on 107 for current Document).

**Comment by HappyGino** [comment]
Ok. re-did the TryCatch with curly brackets fix with space and got errors down to 88. Got a small idea of what happened, Some brackets inside brackets do not need space while external ones need spacing and sometimes it's the other way around. Will check on the others and see what happens.

**Comment by KennethGF** [comment]
Thanks

ken

**Comment by HappyGino** [comment]
Had too much windows open in VS. The error count was doubled, even tripled so I closed those many opened windows and got down to 3 errors, one which this same one from up here about the 4 TryCatch in SystemRuntime and System.Reflection.RuntimeMethodInfo and CombatWindow, line 103 and 129,

**Comment by HappyGino** [comment]
Crashed again with this error message in VS. Thought I had fixed this but looks like it bumped back around turn 97. There is definitely something happening within Combat and later turns. Could it be that someone is declaring war to me or false combat again?

**Comment by bote-reginald** [comment]
"too old" - maybe not relevant anymore
