### ISSUE TITLE
Some buildings in queue are freezing the game

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#414]
I found out that some buildings in the queue list are blocked and I cannot rush them, but when I click for the next turn it brings an unhandled exception. If I cancel them from the list, I can continue to the next turn. I then reinserted them into the queue and rushed them again, and the game could continue on once more. It happened on two occasions that, when some objects jam in the building queue, the game freezes.

For example:
Aquatic Deuterium Plant
Moon Habitation
--------------------Shows this:
            var app = new ClientApp();
            app.DispatcherUnhandledException += Current_DispatcherUnhandledException;
            app.InitializeComponent();
            _ = app.Run();

**Comment by bote-reginald** [comment]
we had thrown out the management for Duranium e.g. causing this freeze
