### ISSUE TITLE
GraphicDeviceManager

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#415]
GraphicDeviceManager.cs
**Game was freezing on Next Turn (tried many times, same results)  
Tried the suggested changes below
Would not work with one or two { }
Had to change all 4. Code worked.
(Did not have any other freeze or stop on Turn advance)**

}
private void NewMethod()
{
            try { _device.Present(); }
            catch (InvalidOperationException) {} **change for-->**{ }
            catch (DeviceLostException) {}--->{ }
            catch (DeviceNotResetException)  {}--->{ }
            catch (DriverInternalErrorException) {}--->{ }

C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\Supremacy.Xna\GraphicsDeviceManager.cs

**Comment by HappyGino** [comment]
The problem came back again with this new debug version that I installed. I believe, from what I searched, that there could be a typo error somewhere in the code that makes the game stop, probably in the GraphicsDeviceManager
This new formatting up here is good and no errors are reported, except that the game searches for something it cannot find, or does not have the same name (ie: Grahics vs graphics, Devices vs devices etc...) Still searching to find the culprit in the code.

**Comment by KennethGF** [comment]
Also notice a three, or more, second delay now in loading the Intel spy
report screen. This is new since we worked on the weekend. Could it be some
of the changes put in at the end of our Sunday session? Will look for the
delay(s).

ken

**Comment by HappyGino** [comment]
Not only is there a delay but I have to click on Continue a few times to make it roll again.
And then, later on, it freezes and always shows the Try Catch strings.
I’m not even in the Intel yet, I’m just trying to populate the Empire at the moment, getting members to join and open the borders for trade.
Sometimes, it happens near the start of the game (turn 12 to 17) and in other times, later in the game (turn 57 to 60).
I believe it is searching for a word (or words) which is (are) misspelled, or a code string  that has an error in the formatting and advances through until it finds another, and then cumulates up until it cannot go further.
I write that because I noted that the game slows down as it goes further deep (sometimes, 5 to 10 seconds delay and more before changing from a screen to another) and then, crashes down. I did a search for badly written codes but with my poor experience in the subject, I could not find how to do it. Sorry…
Still searching…


Bonne journée! Have a nice day!

De : Kenneth Of Borg<mailto:notifications@github.com>
Envoyé le :11 décembre 2019 09:14
À : BotF2/BotF2<mailto:BotF2@noreply.github.com>
Cc : HappyGino<mailto:emilgo47@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [BotF2/BotF2] GraphicDeviceManager (#415)

Also notice a three, or more, second delay now in loading the Intel spy
report screen. This is new since we worked on the weekend. Could it be some
of the changes put in at the end of our Sunday session? Will look for the
delay(s).

ken

**Comment by HappyGino** [comment]
It may sound bizarre to you but that error reappeared and when I clicked on Pause and continue a few times, I then landed on D3D9 graphics parameters (Framework XNA component?)
I then went to where it was showing and some parameters are greyed out in the enumeration, as if it wasn't initiated, or not open. Normally, on Windows 10, I think the DirectX component is D3D12.
Could it be missing to detect my D3D, since it's version 12? I looked in the DirectX folder for Visual Studio and there is no reference about D3D12. The newest is D3D11...Could there be an update for version 12 in Visual Studio 2019? 
I could be totally wrong though but it bothers me that the game always freezes at this state...

Gino

**Comment by KennethGF** [comment]
Do see a VS update but not that in that notes. Will you be online Sunday?

ken

**Comment by HappyGino** [comment]
Yes I will be there as usual around 9h AM

Gino

Bonne journée! Have a nice day!

De : Kenneth Of Borg<mailto:notifications@github.com>
Envoyé le :13 janvier 2020 20:19
À : BotF2/BotF2<mailto:BotF2@noreply.github.com>
Cc : HappyGino<mailto:emilgo47@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [BotF2/BotF2] GraphicDeviceManager (#415)

Do see a VS update but not that in that notes. Will you be online Sunday?

ken
