### ISSUE TITLE
Saved games do not hold onto spy network

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#439]
Cannot save the view of empires where you set up a spy network in Spy Report, AssetsScreen. The systems you infiltrated with a spy network is not saved. You need to revisit that again with a spy ship.

**Comment by ExultantMonkey** [comment]
Make sure that where you are storing the data implements Serializable etc

**Comment by KennethGF** [comment]
Thanks, I need to do my homework on how this works.
ken

**Comment by KennethGF** [comment]
The code looks at who is local payer to display a view of other Empires
visited by a spy ship and order to spy. Not sure if the save of that data
will also work for others in a multiplayer game? Do I need to save a list
of others to view for each Empire or just the host?
Trying to grasp the process.
Ken

**Comment by KennethGF** [comment]
ok now, spied list in civmanager
