### ISSUE TITLE
Non existing link error

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#450]
**Pointing to Non existing link (404)**

private readonly IGameErrorService _errorService;
        private const string _reportErrorURL = "https://www.exultantmonkey.co.uk/BotF2/report-error.php";

**I believe this code should be deleted, nullified or changed for another site if one exist**

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0649	Field 'ClientUnhandledExceptionHandler._errorService' is never assigned to, and will always have its default value null	SupremacyClient	C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyClient\ClientUnhandledExceptionHandler.cs	21	Active

**Comment by KennethGF** [comment]
C:\Users\kenne\Documents\89_BOTF2_20191011\SupremacyClient\ClientUnhandledExceptionHandler.cs

**Comment by KennethGF** [comment]
May use this feature of sending error reports in the future.
