### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#453]
**Don't know what happened here...Found a new system (Barzans) and called for a new turn.
I think that I was near the Cardassian system although I couldn't see them yet.**

System.AggregateException
  HResult=0x80131500
  Message=Une ou plusieurs erreurs se sont produites. (One or more errors occurred)
  Source=SupremacyCore
  StackTrace:
   at Supremacy.Game.GameEngine.DoPreTurnOperations(GameContext game) in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyCore\Game\GameEngine.cs:line 399
   at Supremacy.Game.GameEngine.DoTurn(GameContext game) in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyCore\Game\GameEngine.cs:line 215
   at Supremacy.WCF.SupremacyService.<>c__DisplayClass48_0.<DoTurnCore>b__0() in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyService\SupremacyService.cs:line 573
   at System.Linq.Observable.<>c__DisplayClass130.<>c__DisplayClass132.<ToAsync>b__12f()

  This exception was originally thrown at this call stack:
    Supremacy.Diplomacy.DiplomacyHelper.IsContactMade(Supremacy.Entities.Civilization, Supremacy.Entities.Civilization) in DiplomacyHelper.cs
    Supremacy.Game.SectorClaimGrid.GetPerceivedOwner.AnonymousMethod__1(<>f__AnonymousType15<Supremacy.Entities.Civilization, int>) in SectorClaimGrid.cs
	System.Linq.Enumerable.WhereEnumerableIterator<TSource>.MoveNext()
	System.Linq.Buffer<TElement>.Buffer(System.Collections.Generic.IEnumerable<TElement>)
	System.Linq.OrderedEnumerable<TElement>.GetEnumerator()
    Supremacy.Game.SectorClaimGrid.GetPerceivedOwner(Supremacy.Universe.MapLocation, Supremacy.Entities.Civilization) in SectorClaimGrid.cs
    Supremacy.Orbitals.Orbital.Reset() in Orbital.cs
    Supremacy.Orbitals.StationDesign.TrySpawn(Supremacy.Universe.MapLocation, Supremacy.Entities.Civilization, out Supremacy.Tech.TechObject) in StationDesign.cs
    Supremacy.Economy.BuildProject.Finish() in BuildProject.cs
    Supremacy.Orbitals.BuildStationOrder.OnOrderCompleted() in FleetOrders.cs
    ...
    [Call Stack Truncated]
Inner Exception 1:
ArgumentNullException: La valeur ne peut pas être null. (Value cannot be Null)
Nom du paramètre : target

**Comment by KennethGF** [comment]
Want to look closer at diplomacy and iscontactmade. Was getting incorrect
results from it.

ken

**Comment by HappyGino** [comment]
I did 2 commits on my version, one concerning this AggregateException (diplomacy) with  a suggestion from VS. It did not show any errors when I fixed it.
and the other about the way the game closes and exits. Seems to be working now and closing smoothly. Will see later in the game.
