### ISSUE TITLE
CivDatabase is loaded multiple times

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#46]
- SupremacyClient\SinglePlayerStartScreen.xaml\SinglePlayerStartScreen.xaml.cs:49
- SupremacyCore\Game\GameContext.cs:863
- SupremacyCore\Game\GameInitData.cs:261
- SupremacyUI\GalaxyGridPanel.cs:234

Ideally we want to load it only once. The load in GalaxyGridPanel.cs was added to me fix a big with races not being in the current GameContext

**Comment by ExultantMonkey** [comment]
Need to find some way to load a master copy once at startup, then SinglePlayerStartScreen and GalaxyGridPanel can refer to that. GameContext/GameInitData can possibly make a copy of the master to manipulate

**Comment by ExultantMonkey** [comment]
I'm afraid this isn't fixed yet

**Comment by KennethGF** [comment]
Ops, sorry, closed that by mistake.
