### ISSUE TITLE
New AggregateException Error

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#462]
**Not the same as 453 and created an UnhandledException, see below**

System.AggregateException
  HResult=0x80131500
  Message=Une ou plusieurs erreurs se sont produites. (One or more errors have occurred)
  Source=SupremacyCore
  StackTrace:
   at Supremacy.Game.GameEngine.DoPreTurnOperations(GameContext game) in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyCore\Game\GameEngine.cs:line 399
   at Supremacy.Game.GameEngine.DoTurn(GameContext game) in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyCore\Game\GameEngine.cs:line 215
   at Supremacy.WCF.SupremacyService.<>c__DisplayClass48_0.<DoTurnCore>b__0() in C:\Users\Gino\Documents\BOTF2_2019_cot_13_New\SupremacyService\SupremacyService.cs:line 573
   at System.Linq.Observable.<>c__DisplayClass130.<>c__DisplayClass132.<ToAsync>b__12f()

  This exception was originally thrown at this call stack:
	System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource)
	System.Collections.Generic.List<T>.Enumerator.MoveNextRare()
	System.Collections.Generic.List<T>.Enumerator.MoveNext()
    Supremacy.Game.CivilizationManager.SitRepEntries.get() in CivilizationManager.cs
    Supremacy.Economy.BuildProject.Finish() in BuildProject.cs
    Supremacy.Orbitals.BuildStationOrder.OnOrderCompleted() in FleetOrders.cs
    Supremacy.Orbitals.Fleet.Reset() in Fleet.cs
    Supremacy.Game.GameEngine.DoPreTurnOperations.AnonymousMethod__0(Supremacy.Universe.UniverseObject) in GameEngine.cs

Inner Exception 1:
InvalidOperationException: La collection a été modifiée ; l'opération d'énumération peut ne pas s'exécuter. (Collection has been modified. The enumeration operation cannot execute)

**Comment by HappyGino** [comment]
This Aggregate Exception thing causes the game to crash over and over, like if something was missing, and it was searching the cause. I see there are many causes. Some are for Combat when there is none and some about the collection. Some, like here I think, about fleet creating and stacking ships.
I was trying to make fleets in some colonies after the upgrades of the frigates and cruisers. There seem to be a conflict between the old and new ships or old and new buildings, 
Could it be that certain codes or enumeration of some upgraded objects have the same name as the old ones, which would make a conflict between both and crash the game? It seems to be looking for a new name which doesn't exist so in order to finish the turn, it needs to find those differences in names. 
That's what I concluded from playing over and over and having always the same crash (well, almost the same) although with different objects. **I could be wrong though...**
I see up here that as soon as it finds an installed object, it moves to the next, and the next,... until it gets to something that doesn't exist or is badly named (or coded) in the list, 
i.e.: Frigate I vs Frigate II or III, or Automated Farm I vs Automated Farm II and/or III (or whatever upgrade), At some point, I guess there is a conflict between upgrade names in the list.

**Comment by KennethGF** [comment]
Hope it will be one we can track down.
ken

**Comment by HappyGino** [comment]
I'll continue toi check around in the files, so if there is something strange, I will report it.  Hopefully, I will stumble on something by chance...Or by reading here and there...

Gino

**Comment by bote-reginald** [comment]
made a GameLog instead of a crash
