### ISSUE TITLE
About the log file text errors

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#463]
I was looking at the Log file TXT and there seems to be a few problems, one about the CTRL O options (traces) that creates a conflict in VS, and one with not finding the trade routes and returning the credits....to where? Back to the colony or...?? I know it's only a report but it seems curious... As this Research conducting error...
(Traces mostly set to ERRORS only (Press CTRL + O) Is it because it sends all errors to the developpers?

03:42:43.944 [1] INFO  General Supremacy.Utility.GameLog.Initialize() - Log Initialized
03:42:44.024 [1] INFO  General Supremacy.Utility.GameLog.Initialize() - Possible file name prepared... (see next line)
2020-1-1_3-42-44 Gamelog.txt

03:42:44.072 [1] INFO  General Supremacy.Client.ClientApp.CheckNetFxVersion() - .NET Framework 4.7.2 or later found
03:42:44.763 [1] INFO  GameData Supremacy.Resources.ResourceManager..cctor() - Hint: local file \Data\xx.txt not available - at the moment only English (en.txt) is ingame. French and German are already done
03:42:44.790 [1] INFO  General Supremacy.Client.ClientSettings.set_TracesClearAll() - Log.Txt: Traces mostly set to ERROR only (press ingame CTRL + O)
03:43:03.036 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
03:43:36.938 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
03:44:11.063 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
03:46:43.427 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
03:47:34.136 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
03:49:41.771 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
03:50:50.399 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
03:51:04.026 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
03:53:35.501 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
03:55:23.569 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
03:55:41.405 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
03:55:56.802 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
03:59:54.600 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
04:00:26.251 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
04:03:16.149 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
04:03:28.923 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 50 credits
04:04:09.694 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 50 credits
04:10:13.068 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
04:14:39.474 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
04:14:59.013 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
04:15:07.895 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 30 credits
04:18:10.842 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
04:18:48.187 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
04:19:00.694 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
04:19:36.485 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
04:23:54.958 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 40 credits
04:24:03.426 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 50 credits
04:25:00.790 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 50 credits
04:30:25.448 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 50 credits
04:30:52.435 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 50 credits
04:31:07.356 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 50 credits
04:36:09.643 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 60 credits
04:41:54.290 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 60 credits
04:42:27.887 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 60 credits
04:48:35.593 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 60 credits
04:48:51.401 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 60 credits
04:49:00.679 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
04:49:40.040 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
04:54:57.332 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
04:55:24.462 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
04:56:20.074 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
04:57:49.268 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
04:58:46.020 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 90 credits
04:58:58.651 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 90 credits
05:07:40.242 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
05:14:46.050 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 10 credits
05:15:00.341 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
05:15:25.597 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
05:16:25.298 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
05:16:33.787 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
05:23:29.032 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
05:23:35.099 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
05:24:40.340 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
05:25:34.861 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
05:25:48.221 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
05:33:45.485 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
05:39:36.954 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 90 credits
05:40:44.604 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
05:41:14.405 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 90 credits
05:49:01.525 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
05:49:12.082 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 20 credits
05:50:07.521 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 90 credits
05:50:51.173 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 90 credits
05:51:09.460 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
05:59:39.562 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
05:59:49.882 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
05:59:57.655 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:00:10.547 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:08:11.259 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:08:16.155 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
06:17:02.484 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
06:17:38.989 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
06:18:07.364 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
06:26:03.498 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
06:26:26.480 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
06:27:47.154 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
06:28:10.935 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
06:28:43.175 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
06:37:58.419 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
06:38:05.794 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
06:38:53.323 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
06:39:24.719 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 10 credits
06:39:39.044 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 70 credits
06:39:46.093 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:40:05.761 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 10 credits
06:40:09.026 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 10 credits
06:40:24.241 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:41:03.471 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 20 credits
06:41:19.002 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:49:17.912 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:49:30.443 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:50:31.236 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:50:39.803 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:51:12.753 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
06:51:15.577 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
06:51:17.556 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
06:51:38.372 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
06:51:48.847 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
06:51:56.149 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:52:10.615 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
06:52:19.777 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:59:30.351 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:59:41.228 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
06:59:53.163 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
07:00:06.714 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
07:00:33.786 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
07:09:48.162 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
07:10:02.582 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
07:10:19.219 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
07:10:41.731 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 20 credits
07:10:52.665 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
07:11:52.627 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 10 credits
07:12:01.022 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 20 credits
07:12:04.926 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
07:12:14.348 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
07:12:31.976 [29] ERROR Research Supremacy.Game.GameEngine+<>c__DisplayClass35_0.<DoResearch>b__1() - There was a problem conducting research for 707 USS Da Vinci
07:12:33.574 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 80 credits
07:12:54.581 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
07:13:06.464 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits
07:13:10.142 [1] ERROR General Supremacy.Universe.TradeRoute.get_LocalPlayerCredits() - #### problem with ServiceLocator.Current.GetInstance<IClientContext>(), returning 0 credits

**Comment by bote-reginald** [comment]
Traces (CTRL+O) are like a turn on/off, Category Error is always on, Debug > set this at CTRL+O

Some errors are not nice, but not totally relevant ...for these we do not want the game crash

For real it depends on how the trace is coded - some at category "Test", some at Trade Routes and so on ... for this have a look to the code 
Traces help knowing where the code is and what's going on ... and as coded, some errors shown as well.
I use Log.txt- entries for a quick find of code > ", returning" could give you very quick the place in the code  of returning credits from Trade Routes.

We will have a look to this as soon as possible - normally Trade Routes are between two colonies

**Comment by HappyGino** [comment]
Oh Ok Thank you Reg!
I better understand now how Traces work. All those boxes (On or Off) indicate the things you want to see or not in the log file. So Trade Routes indicate where the credits are sent and returned to.
I will check around with this Trace option and VS. So long as it doesn't crash the game, it's Ok then.
I will wake up more wise than yesterday, lol.
