### ISSUE TITLE
Save game button not active

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#465]
Steve: "I may have noticed something that would help you find where the code is broken for "Save Game." I'm talking about the save button that won't brighten up when you open up "save game." What I realized is that it doesn't light up at the end of a turn but it DOES light up if you make a few more system changes or even one change (Like picking a new ship to manufacture or adding something to the build list). So there is a variable that is set to "ON" when you make system changes that is NOT on at the end of a turn."

**Comment by HappyGino** [comment]
Ok. Sorry for my ignorance on the subject,
Feels to me that there is a code, or a function that takes a snapshot, a capture of the moment each time you click on Save, and copies it in a file, and in that this function or code, there could be a misspelling or a missing word, or a double space, whatever, (I'm thinking of my music files which had a double space and that the player couldn't read or a file that had a wrong letter in the name). You never know...
