### ISSUE TITLE
Medical ships doing nothing, except in Federation

### ISSUE THREAD

**Issue by HappyGino** [BotF2/BotF2#466]
I was playing with many Civs and I found out that, except for the Federation, Medical ships don't get the health to rise, be it in the Home planet or a joined member. The Medical ships don't seem to do anything when they're assigned to send medical supplies. They just sit there doing nothing...even after 30 turns...Odd... 
It still grows with the help from immunology building (like 2%) but the health (80) and morale not raising (Morale 98 to 101).
The members and the home system colonies go Apathetic and stay that way.

**Comment by KennethGF** [comment]
We should also look at the data base and see what all medical ships have
for values. Could be some medical value shortfall. TechObjectDatabase.xml

ken

**Comment by HappyGino** [comment]
There's something I found while playing as the Romulans. If I use 2 medical ships and create a fleet, it then starts to give health to the planet. By using only one, it doesn't do anything. 
At least, something is happening here...
And one other thing, with the Romulans, my demands for joining us or anything else (Open borders, non agressive pact...) succeed every time,  
Will try with other Enpires and see what happens.

**Comment by KennethGF** [comment]
code update with fix
