### ISSUE TITLE
Two systems called Gamma Velorum, Universe generator

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#489]
![2020-07-03 14_51_26-Window](https://user-images.githubusercontent.com/5161174/86499151-634f8800-bd3e-11ea-8e2e-480b6d5521da.png)
![2020-07-03 14_51_59-Window](https://user-images.githubusercontent.com/5161174/86499153-664a7880-bd3e-11ea-9a1a-9af6210e745d.png)

**Comment by bote-reginald** [comment]
guess I solved it 24 JUL 2021 - not committed yet
