### ISSUE TITLE
Minor races & Empires Diplomatic Reports

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#5]
We need to put the diplomatic reports in the Embassy screen

![image](https://user-images.githubusercontent.com/33752261/34461690-44ffa68c-ee29-11e7-9bde-ab77f65d6155.png)

**Comment by KennethGF** [comment]
Added the first contact diplomatic report info to the screen under the race image. Can move it into a race info button at some point in the future.
