### ISSUE TITLE
Game Logging Revamp

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#60]

**Comment by ExultantMonkey** [comment]
I have worked out the best way to do this, builds on the tidying up of the command line options I did in 5250c05acb6f623b0262cdb25b2778ae8106aa30

**Comment by bote-reginald** [comment]
Thanks. Is there a way to activate some additional logging (e.g. command line arg.  = -TraceLevel:High) ?

**Comment by ExultantMonkey** [comment]
Yes, -Traces=Intel,Diplomacy will activate debug messages for Intel and Diplomacy for example, -Traces=AI will activate debug messages for AI

**Comment by bote-reginald** [comment]
just for info to anyone: this is the current available list: -Traces:AI,Audio,Combat,Diplomacy,Events,Intel,GalaxyGenerator,GameData,General,Production,ShipProduction

**Comment by KennethGF** [comment]
see GameLog.cs and class Repositories: properties
