### ISSUE TITLE
Wormhole Improvements

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#67]
- [ ] Possibly require investigation with a science ship before use
- [ ] Have some way to display which wormholes have been explored and are stable/unstable, and where they go
- [ ] Add Barzan wormhole
- [ ] Add possibility of wormhole ends moving about
- [ ] Always have Bajorans in game for the Bajoran Wormhole (#98)
- [ ] Check wormhole name formatting

Merging all the wormhole issues in with this one (#97)

**Comment by KennethGF** [comment]
agree

**Comment by DanOfStarfleet** [comment]
In the old BOTF game, some ships are destroyed because some wormholes have no exit

**Comment by ExultantMonkey** [comment]
@DanOfStarfleet that is the case at the moment, although it doesn't tell the player

**Comment by bote-reginald** [comment]
atm I guess Wormholes are working fine ... some connected to the other side, some to nowhere > no further issue atm
