### ISSUE TITLE
Intel/Diplomacy Map Data

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#68]
Add the ability to steal map data.
Making alliances etc can reveal map data. 
Use map data as a bargaining chip in diplomatic agreements

**Comment by KennethGF** [comment]
This is a concept very dear to me. I have long wanted to increase the fog of war and then us intel to get view of ship movement for other empires, location of trade routs (and points where a ship could cut trade), location of colonies and allies, detail on colonies like shipyards.... Want to use it so intel is a better tool.

**Comment by KennethGF** [comment]
Consider getting rid of the intel as a UI screen and let the spy ships do intel jobs on the galactic map.

**Comment by bote-reginald** [comment]
the longer the game runs the more own map data is available
