### ISSUE TITLE
Processing Production

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#78]
Have noted some random failures to progress from Processing Production on Processing Turn. Need to get some game logs into system production to see if it can be isolated.

**Comment by KennethGF** [comment]
Appear to be able to cause a freeze in the processing production step by altering the value of TaxCredits in Colony.cs 
Will be looking into credits as a whole.

**Comment by KennethGF** [comment]
Was able to get a stackoverflow error in percentages.cs  ApplyErrorCorrectionAndLimitPrecision(ref float value) and Percentage(float value) by putting in higher values for OutputModifier(0, 1.0f); in TaxCredits() of colony.cs

**Comment by KennethGF** [comment]
DoProcution infinity loop when raw material = 0 for building a Fed orbital battery

**Comment by ExultantMonkey** [comment]
That should be hopefully be enough to narrow it down On 11 Aug 2018 17:43, Kenneth Of Borg <notifications@github.com> wrote:DoProcution infinity loop when raw material = 0 for building a Fed orbital battery

**Comment by KennethGF** [comment]
appeared to be the While loop in DoProduction when there was zero rawmaterial. While condition always true for the loop.
