### ISSUE TITLE
Build context menu for all races

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#8]

**Comment by KennethGF** [comment]
Only the Dominion remains on the old Federation popup Context Menu. Klingon, Federation and Terran remain on a small image format that could be enlarged to as much as 560 x 560.

**Comment by KennethGF** [comment]
Well along with the Dominion.

**Comment by KennethGF** [comment]
We have this now. Can always improve the look but will leave that for some artists to do.
