### ISSUE TITLE
Medical Ships

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#90]
If we have medical ships lets put them to use. Want medical situations that require a Ship to fix.

**Comment by ExultantMonkey** [comment]
There is stuff in the code somewhere for plagues etc.

For the science ships, maybe we could require at least one end of a wormhole to be stabilised before use?

**Comment by KennethGF** [comment]
Good ideas. Think you get some bonus from sending science ships to
interesting locations to study and medical ships to systems to improve the
population health. Would like to link medical ships as needed to clear a
plague and science ships to make some required breakthrough for tech
leveling up. ? Grand unification theory or dark energy or some trekish
technobable gibberish.

ken

**Comment by KennethGF** [comment]
OK for now
