### ISSUE TITLE
Transport Order Freeze

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#91]
In testing noted, for the raid transports order, the combat freezes. This happened in both multi-player and single-player.

06:20:38.115 [8] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): 113 USS Avenger attacking 201 CDS dsConquest
06:20:38.115 [8] DEBUG General - AutomatedCombatEngine.PerformAttack(): 201 CDS dsConquest was destroyed
06:20:38.116 [8] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): Target for 107 USS Antares is 217 CDS tParentage
06:20:38.117 [8] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): 107 USS Antares attacking 217 CDS tParentage
06:20:38.118 [8] DEBUG General - AutomatedCombatEngine.PerformAttack(): 217 CDS tParentage was destroyed
06:20:38.124 [8] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): Target for 111 USS Atlantis is 199 CDS dsCaravan
06:20:38.124 [8] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): 111 USS Atlantis attacking 199 CDS dsCaravan
06:20:38.125 [8] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): CDS c	Challenger 207 hailing...
06:20:38.126 [8] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): CDS c	Charger 209 hailing...
06:20:38.133 [21] DEBUG General - SupremacyService.SendCombatUpdateCallback(): Generating fake order for Cardassians
06:20:38.134 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): 197 CDS dsAdventurer is ordered to Engage
06:20:38.135 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): 199 CDS dsCaravan is ordered to Engage
06:20:38.136 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): 203 CDS dsDiscovery is ordered to Engage
06:20:38.137 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): 205 CDS c Avenger is ordered to Engage
06:20:38.137 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): 207 CDS c	Challenger is ordered to Engage
06:20:38.138 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): 209 CDS c	Charger is ordered to Engage
06:20:38.138 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): 211 CDS c	Conqueror is ordered to Engage
06:20:38.138 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): 219 CDS tProgenitor is ordered to Engage
06:20:38.139 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): 221 CDS Ancestor is ordered to Engage
06:20:38.139 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): 223 CDS oo1	Obsidian is ordered to Engage
06:20:38.140 [21] DEBUG General - CombatHelper.GenerateBlanketOrders(): CARD_OUTPOST_II is ordered to Engage
06:20:40.539 [1] DEBUG General - CombatWindow.OnOrderButtonClicked(): OnOrderButtonClicked:  Combat Window: Order Button clicked by Player = Transports
06:20:40.541 [1] DEBUG General - CombatHelper.GenerateBlanketOrders(): 105 USS Adventure is ordered to Transports
06:20:40.542 [1] DEBUG General - CombatHelper.GenerateBlanketOrders(): 107 USS Antares is ordered to Transports
06:20:40.542 [1] DEBUG General - CombatHelper.GenerateBlanketOrders(): 109 USS Battler is ordered to Transports
06:20:40.543 [1] DEBUG General - CombatHelper.GenerateBlanketOrders(): 111 USS Atlantis is ordered to Transports
06:20:40.544 [1] DEBUG General - CombatHelper.GenerateBlanketOrders(): 113 USS Avenger is ordered to Transports
06:20:40.544 [1] DEBUG General - CombatHelper.GenerateBlanketOrders(): 115 USS Discovery is ordered to Transports
06:20:40.545 [1] DEBUG General - CombatHelper.GenerateBlanketOrders(): 117 USS Patton is ordered to Transports
06:20:40.546 [1] DEBUG General - CombatHelper.GenerateBlanketOrders(): 119 USS No Name is ordered to Transports
06:20:40.546 [1] DEBUG General - CombatHelper.GenerateBlanketOrders(): 121 USS Sussex is ordered to Transports
06:20:40.547 [1] DEBUG General - CombatHelper.GenerateBlanketOrders(): 123 USS Chino is ordered to Transports
06:20:40.549 [42] DEBUG General - CombatEngine.CalculateEmpireStrengths(): Strength for FEDERATION = 1384
06:20:40.550 [42] DEBUG General - CombatEngine.CalculateEmpireStrengths(): Strength for CARDASSIANS = 1837
06:20:40.550 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): Target for 209 CDS c	Charger is 105 USS Adventure
06:20:40.551 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): 209 CDS c	Charger attacking 105 USS Adventure
06:20:40.552 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): Target for 105 USS Adventure is 219 CDS tProgenitor
06:20:40.553 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): 105 USS Adventure attacking 219 CDS tProgenitor
06:20:40.555 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): Target for 219 CDS tProgenitor is 105 USS Adventure
06:20:40.556 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): 219 CDS tProgenitor attacking 105 USS Adventure
06:20:40.557 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): Target for 123 USS Chino is 219 CDS tProgenitor
06:20:40.558 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): 123 USS Chino attacking 219 CDS tProgenitor
06:20:40.559 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): Target for 121 USS Sussex is 219 CDS tProgenitor
06:20:40.560 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): 121 USS Sussex attacking 219 CDS tProgenitor
06:20:40.561 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): Target for 111 USS Atlantis is 219 CDS tProgenitor
06:20:40.562 [42] DEBUG General - AutomatedCombatEngine.ResolveCombatRoundCore(): 111 USS Atlantis attacking 219 CDS tProgenitor
06:20:40.563 [42] DEBUG General - AutomatedCombatEngine.PerformAttack(): 219 CDS tProgenitor was destroyed

**Comment by ExultantMonkey** [comment]
Will look in to now

**Comment by ExultantMonkey** [comment]
Think I've figured it out. It's a boo boo on my part :)

**Comment by ExultantMonkey** [comment]
Hopefully f90555f51147e3892545326e972a90f55b2bfa22 fixes it

**Comment by KennethGF** [comment]
Wonderful
Thanks yet again

ken

**Comment by ExultantMonkey** [comment]
There is another infinite loop in there, but it's not in the code for the rush order - it's somewhere else in the combat code, which can give the appearance that it's the rush order. It should be fixed now
