### ISSUE TITLE
Wormhole names bug

### ISSUE THREAD

**Issue by ExultantMonkey** [BotF2/BotF2#97]
Reported by @DanOfStarfleet in private message

We have a bug about the wormhole names! (for the Bajoran & Quadrants Names). In the en.txt file we have only:

[WORMHOLE_NAME_FORMAT]
{0} Wormhole

My proposition is to also add the following:

[WORMHOLE_BAJORAN_NAME_FORMAT]
Bajoran Wormhole

[WORMHOLE_GAMMA_NAME_FORMAT]
Gamma Quadrant Wormhole

[WORMHOLE_BETA_NAME_FORMAT]
Beta Quadrant Wormhole

[WORMHOLE_ALPHA_NAME_FORMAT]
Alpha Quadrant Wormhole

[WORMHOLE_DELTA_NAME_FORMAT]
Delta Quadrant Wormhole

![wormhole_bug](https://user-images.githubusercontent.com/33752261/43957882-5747a75a-9ca1-11e8-8970-4ae7abdfdbdf.jpg)

**Comment by DanOfStarfleet** [comment]
Notice this: the minor race Barzan own also their wormhole

**Comment by ExultantMonkey** [comment]
For the Barzan wormhole, could possibly have it dump the ships out at a completely random location?

**Comment by KennethGF** [comment]
Like the random location idea

**Comment by ExultantMonkey** [comment]
Merged in to #67
